Repository 0xERR0R/blocky, pull requests merged in 2021-05, with the labels that each got.

#198 Make prefetch fully configurable
  config/config.go
  docs/config.yml
  docs/configuration.md
  resolver/caching_resolver.go
  resolver/caching_resolver_test.go
Labels: documentation, enhancement

#199 WhitelistOnly Fix for multiple entries
  resolver/blocking_resolver.go
  resolver/blocking_resolver_test.go
Labels: bug

#195 Added version to web interface.
  .goreleaser.yml
  Makefile
  cmd/root.go
  cmd/serve.go
  cmd/version.go
  go.mod
  go.sum
  server/server_endpoints.go
  util/buildinfo.go
  web/index.go
Labels: enhancement

#211 Make the number of cached domains configurable
  config/config.go
  docs/config.yml
  docs/configuration.md
  go.mod
  go.sum
  resolver/caching_resolver.go
  resolver/caching_resolver_test.go
  resolver/client_names_resolver.go
Labels: enhancement
