Repository 0xERR0R/blocky, pull requests merged in 2022-09, with the labels that each got.

#636 Blocky should start resolving DNS traffic as soon as possible(#566)
  config/config.go
  config/config_enum.go
  config/config_test.go
  docs/config.yml
  docs/configuration.md
  lists/list_cache.go
  lists/list_cache_benchmark_test.go
  lists/list_cache_test.go
  querylog/database_writer_test.go
  resolver/blocking_resolver.go
  resolver/blocking_resolver_test.go
Labels: enhancement

#640 Updated CodeQL to v2
  .github/workflows/codeql-analysis.yml
Labels: dependencies

#639 Change self-signed cert to ECDSA
  server/server.go
Labels: enhancement

#648 add grafana template for Postgres
  docs/blocky-query-grafana-postgres.json
  docs/prometheus_grafana.md
Labels: documentation, enhancement

#589 Add connectIPVersion to choose how Blocky connects to other hosts
  config/config.go
  config/config_enum.go
  docs/config.yml
  docs/configuration.md
  resolver/bootstrap.go
Labels: enhancement

#613 chore: update Golang 1.19
  go.mod
Labels: dependencies

#645 Special-Use Domain Names (#635)
  go.mod
  go.sum
  model/models.go
  model/models_enum.go
  resolver/blocking_resolver.go
  resolver/blocking_resolver_test.go
  resolver/ede_resolver.go
  resolver/resolver.go
  resolver/sudn_resolver.go
  resolver/sudn_resolver_test.go
  resolver/upstream_resolver_test.go
  server/server.go
Labels: enhancement

#656 Ignore non YAML and non regular files when loading configs from a directory
  config/config.go
  config/config_test.go
Labels: enhancement
