Repository 0xERR0R/blocky, pull requests merged in 2022-11, with the labels that each got.

#714 chore: add dependabot configuration for github actions
  .github/dependabot.yml
Labels: dependencies

#651 GitHub workflow rework
  .dockerignore
  .github/workflows/ci-build.yml
  .github/workflows/close_stale.yml
  .github/workflows/development-docker.yml
  .github/workflows/release.yml
  .gitignore
  Dockerfile
  Makefile
  cmd/version.go
  go.mod
  go.sum
  tools.go
  util/buildinfo.go
Labels: technical debts

#731 feat: caching for empty DNS responses (#700)
  config/config_enum.go
  docs/config.yml
  docs/configuration.md
  lists/list_cache_enum.go
  log/logger_enum.go
  model/models_enum.go
  resolver/caching_resolver.go
  resolver/caching_resolver_test.go
Labels: enhancement

#741 fix: add timezone data to docker container
  main_static.go
Labels: bug

#742 Use either /etc/localtime or TZ in Docker containers
  main_static.go
Labels: bug

#757 [Feature]: Support for redis sentinel(#632)
  config/config.go
  docs/config.yml
  docs/configuration.md
  redis/redis.go
Labels: enhancement

#761 Improvements redis test
  redis/redis.go
  redis/redis_test.go
Labels: technical debts

#756 queryLog: log instance hostname or identifier to distinguish log entries in multi-instance installation(#319)
  docs/installation.md
  querylog/database_writer.go
  querylog/file_writer.go
  querylog/file_writer_test.go
  querylog/logger_writer.go
  util/hostname.go
  util/hostname_test.go
Labels: enhancement

#753 e2e integration tests with docker and testcontainers
  .dockerignore
  .github/workflows/e2e-tests.yml
  .gitignore
  .golangci.yml
  Dockerfile
  Makefile
  e2e/basic_test.go
  e2e/blocking_test.go
  e2e/containers.go
  e2e/e2e_suite_test.go
  e2e/metrics_test.go
  e2e/querylog_test.go
  e2e/redis_test.go
  e2e/upstream_test.go
  go.mod
  go.sum
  helpertest/helper.go
Labels: technical debts

#767 chore(build): disable deprecated linters
  .golangci.yml
Labels: technical debts

#766 feat: querylog: define which information should be logged (#765)
  config/config.go
  config/config_enum.go
  docs/config.yml
  docs/configuration.md
  go.mod
  go.sum
  querylog/database_writer.go
  querylog/database_writer_test.go
  querylog/file_writer.go
  querylog/file_writer_test.go
  querylog/logger_writer.go
  querylog/logger_writer_test.go
  querylog/writer.go
  resolver/query_logging_resolver.go
  resolver/query_logging_resolver_test.go
Labels: enhancement

#774 chore(build): add additional linters
  .golangci.yml
  cache/stringcache/string_caches_benchmark_test.go
  cmd/root.go
  config/config.go
  evt/events.go
  helpertest/helper.go
  lists/list_cache_test.go
  log/logger.go
  metrics/metrics.go
  redis/redis.go
  resolver/blocking_resolver.go
  resolver/bootstrap.go
  resolver/bootstrap_test.go
  resolver/hosts_file_resolver.go
  resolver/hosts_file_resolver_test.go
  resolver/noop_resolver.go
  resolver/query_logging_resolver.go
  resolver/rewriter_resolver.go
  resolver/upstream_resolver.go
  resolver/upstream_resolver_test.go
  server/server.go
Labels: technical debts
