Repository 0xERR0R/blocky, pull requests merged in 2022-05, with the labels that each got.

#509 chore: test cleanup and refactoring
  .github/workflows/ci-build.yml
  Makefile
  cache/expirationcache/expiration_cache.go
  cmd/blocking.go
  cmd/blocking_test.go
  cmd/cmd_suite_test.go
  cmd/lists.go
  cmd/lists_test.go
  cmd/query.go
  cmd/query_test.go
  cmd/root.go
  cmd/serve.go
  cmd/serve_test.go
  go.mod
  go.sum
  helpertest/helper.go
  resolver/blocking_resolver.go
  resolver/blocking_resolver_test.go
  resolver/bootstrap_test.go
  resolver/caching_resolver_test.go
  resolver/client_names_resolver.go
  resolver/client_names_resolver_test.go
  resolver/conditional_upstream_resolver_test.go
  resolver/mocks.go
  resolver/parallel_best_resolver.go
  resolver/parallel_best_resolver_test.go
  resolver/resolver_suite_test.go
  resolver/upstream_resolver_test.go
  server/server.go
  server/server_test.go
Labels: technical debts

#510 update golangci-lint
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  api/api_endpoints_test.go
  cache/expirationcache/expiration_cache.go
  cache/stringcache/string_caches.go
  cmd/lists.go
  cmd/query.go
  cmd/root.go
  cmd/serve.go
  config/config.go
  config/config_test.go
  lists/downloader.go
  lists/list_cache.go
  lists/list_cache_test.go
  querylog/database_writer_test.go
  querylog/file_writer.go
  redis/redis.go
  resolver/blocking_resolver.go
  resolver/blocking_resolver_test.go
  resolver/bootstrap.go
  resolver/bootstrap_test.go
  resolver/caching_resolver.go
  resolver/caching_resolver_test.go
  resolver/client_names_resolver.go
  resolver/conditional_upstream_resolver.go
  resolver/custom_dns_resolver.go
  resolver/hosts_file_resolver.go
  resolver/mocks.go
  resolver/parallel_best_resolver.go
  resolver/parallel_best_resolver_test.go
  resolver/query_logging_resolver.go
  resolver/rewriter_resolver.go
  resolver/rewriter_resolver_test.go
  resolver/upstream_resolver.go
  resolver/upstream_resolver_test.go
  server/server.go
  server/server_endpoints.go
  server/server_test.go
  util/common.go
Labels: dependencies

#514 Memory optimization internal blacklist/whitelist cache (#513)
  cache/stringcache/string_caches.go
  cache/stringcache/string_caches_benchmark_test.go
  cache/stringcache/string_caches_test.go
  util/common.go
  util/common_test.go
Labels: enhancement

#515 Cache refresh memory consumption optimization (#470)
  config/config.go
  docs/configuration.md
  lists/list_cache.go
  lists/list_cache_benchmark_test.go
  lists/list_cache_test.go
  resolver/blocking_resolver.go
Labels: enhancement

#519 Enable "ForceAttemptHTTP2" for DoH upstreamClient
  resolver/upstream_resolver.go
Labels: enhancement

#520 Improve DoT server TLS cipher suites
  server/server.go
Labels: enhancement

#516 add additional logging context (#482)
  resolver/upstream_resolver.go
  resolver/upstream_resolver_test.go
  server/server.go
Labels: enhancement

#518 Hide DoH client http header "User-Agent"
  resolver/upstream_resolver.go
Labels: enhancement

#524 Use same minimum TLS version & cipher for DoH server as DoT server
  server/server.go
Labels: enhancement

#525 Adds user customizable DoH upstream user agent
  config/config.go
  config/config_test.go
  docs/configuration.md
  resolver/upstream_resolver.go
  testdata/config.yml
Labels: enhancement

#532 Self-signed certificate generation
  config/config.go
  config/config_test.go
  docs/config.yml
  docs/configuration.md
  server/server.go
  server/server_test.go
Labels: enhancement

#536 Remove net.Error.Temporary
  lists/downloader.go
  resolver/upstream_resolver.go
Labels: technical debts

#540 Update to Go 1.18
  .github/workflows/ci-build.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
  go.mod
  lists/list_cache_test.go
Labels: technical debts
