Repository 0xERR0R/blocky, pull requests merged in 2022-08, with the labels that each got.

#610 Fix flaky test(537) - second hunt
  cmd/serve_test.go
  config/config_test.go
  go.mod
  go.sum
  lists/downloader_test.go
  querylog/file_writer.go
  querylog/file_writer_test.go
  resolver/blocking_resolver_test.go
  resolver/query_logging_resolver_test.go
Labels: technical debts

#603 Disable colors when not in interactive terminal
  log/logger.go
Labels: enhancement

#617 Managing of external tools with go modules (#616)
  .github/workflows/golangci-lint.yml
  Makefile
  config/config.go
  go.mod
  go.sum
  lists/list_cache.go
  log/logger.go
  model/models.go
  tools.go
Labels: dependencies, technical debts

#619 Define golang version only in go.mod (#618)
  .github/workflows/ci-build.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/release.yml
  Dockerfile
Labels: dependencies, technical debts

#620 chore: switch to codecov GitHub Action
  .github/workflows/ci-build.yml
Labels: technical debts

#611 [Feature Request] delivery of blocking group as EDNS error(560)
  .gitignore
  config/config.go
  docs/config.yml
  docs/configuration.md
  resolver/ede_resolver.go
  resolver/ede_resolver_test.go
  server/server.go
Labels: enhancement

#624 Dynamic unit test data
  .dockerignore
  config/config_test.go
  go.sum
  helpertest/tmpdata.go
  querylog/file_writer_test.go
  resolver/blocking_resolver_test.go
  resolver/hosts_file_resolver_test.go
  resolver/query_logging_resolver_test.go
  server/server_test.go
  testdata/cert.pem
  testdata/config.yml
  testdata/config/config1.yaml
  testdata/config/config2.yaml
  testdata/doubleclick.net.txt
  testdata/heise.de.txt
  testdata/hosts.txt
  testdata/key.pem
  testdata/www.bild.de.txt
  testdata/youtube.com.txt
Labels: technical debts

#631 chore: update golangci-lint
  .golangci.yml
  cmd/lists.go
  cmd/query.go
  cmd/root_test.go
  config/config.go
  go.mod
  go.sum
  helpertest/helper.go
  lists/list_cache_test.go
  log/logger.go
  querylog/file_writer.go
  resolver/mocks.go
  resolver/upstream_resolver.go
  server/server_endpoints.go
  server/server_test.go
  web/index.go
Labels: dependencies

#634 Filter loopback addresses from hosts file
  config/config.go
  docs/config.yml
  docs/configuration.md
  go.mod
  go.sum
  resolver/hosts_file_resolver.go
  resolver/hosts_file_resolver_test.go
Labels: enhancement
