Repository 0xERR0R/blocky, pull requests merged in 2022-06, with the labels that each got.

#545 Add HTTP Secure Headers on HTTPS server response
  server/server.go
  server/server_endpoints.go
Labels: enhancement

#553 Rename securityHeader -> secureHeader
  server/server_endpoints.go
Labels: documentation, enhancement, technical debts

#546 Make DoH/DoT server mininum TLS version configurable
  config/config.go
  config/config_test.go
  docs/config.yml
  docs/configuration.md
  server/server.go
  testdata/config.yml
  testdata/config/config2.yaml
Labels: enhancement

#567 Fix race condition in test
  config/config.go
Labels: technical debts

#574 docs: fix `filterUnmappedTypes` example
  docs/configuration.md
Labels: documentation

#580 set host header for DoH requests
  resolver/upstream_resolver.go
Labels: bug

#581 set content-type header for HTTP endpoints
  api/api_endpoints.go
  api/api_endpoints_test.go
  helpertest/helper.go
  server/server_endpoints.go
  server/server_test.go
Labels: bug
