Repository 0xERR0R/blocky, pull requests merged in 2022-12, with the labels that each got.

#778 fix(ede-resolver): don't panic when next resolver errors
  resolver/ede_resolver.go
  resolver/ede_resolver_test.go
Labels: bug

#771 Config restructuring
  cmd/root.go
  cmd/serve.go
  config/config.go
  config/config_test.go
  docs/config.yml
  docs/configuration.md
  e2e/basic_test.go
  e2e/blocking_test.go
  e2e/metrics_test.go
  e2e/querylog_test.go
  e2e/redis_test.go
  e2e/upstream_test.go
  log/logger.go
  server/server.go
  server/server_test.go
  util/common.go
Labels: enhancement, technical debts

#762 feat: reduce bulk size in database writer (#733)
  go.mod
  go.sum
  querylog/database_writer.go
  querylog/database_writer_test.go
Labels: enhancement

#792 test: use 'eventually' to avoid flaky tests
  e2e/metrics_test.go
Labels: technical debts

#804 fix: no initial cache refresh with "fast" start strategy
  lists/list_cache.go
  resolver/blocking_resolver_test.go
Labels: bug

#798 Test refactoring
  e2e/basic_test.go
  e2e/blocking_test.go
  e2e/metrics_test.go
  e2e/querylog_test.go
  e2e/redis_test.go
  e2e/upstream_test.go
  go.mod
  go.sum
  helpertest/helper.go
  resolver/blocking_resolver.go
  resolver/blocking_resolver_test.go
  resolver/bootstrap_test.go
  resolver/caching_resolver.go
  resolver/caching_resolver_test.go
  resolver/client_names_resolver_test.go
  resolver/conditional_upstream_resolver_test.go
  resolver/custom_dns_resolver_test.go
  resolver/ede_resolver_test.go
  resolver/filtering_resolver_test.go
  resolver/fqdn_only_resolver.go
  resolver/fqdn_only_resolver_test.go
  resolver/hosts_file_resolver.go
  resolver/hosts_file_resolver_test.go
  resolver/metrics_resolver_test.go
  resolver/noop_resolver_test.go
  resolver/parallel_best_resolver_test.go
  resolver/query_logging_resolver_test.go
  resolver/sudn_resolver_test.go
  resolver/upstream_resolver_test.go
  server/server_test.go
Labels: technical debts
