Repository 0xERR0R/blocky, pull requests merged in 2022-03, with the labels that each got.

#447 Update to gingko v2
  api/api_endpoints_test.go
  api/api_suite_test.go
  cache/expirationcache/expiration_cache_suite_test.go
  cache/expirationcache/expiration_cache_test.go
  cache/stringcache/string_cache_suite_test.go
  cache/stringcache/string_caches_test.go
  cmd/blocking_test.go
  cmd/cmd_suite_test.go
  cmd/lists_test.go
  cmd/query_test.go
  cmd/root_test.go
  cmd/serve_test.go
  cmd/version_test.go
  config/config_suite_test.go
  config/config_test.go
  go.mod
  go.sum
  lists/list_cache_test.go
  lists/list_suite_test.go
  querylog/database_writer.go
  querylog/database_writer_test.go
  querylog/file_writer.go
  querylog/file_writer_test.go
  querylog/logger_writer.go
  querylog/logger_writer_test.go
  querylog/none_writer.go
  querylog/none_writer_test.go
  querylog/querylog_suite_test.go
  querylog/writer.go
  redis/redis_suite_test.go
  redis/redis_test.go
  resolver/blocking_resolver_test.go
  resolver/caching_resolver_test.go
  resolver/client_names_resolver_test.go
  resolver/conditionall_upstream_resolver_test.go
  resolver/custom_dns_resolver_test.go
  resolver/hosts_file_resolver_test.go
  resolver/ipv6_disabling_resolver_test.go
  resolver/metrics_resolver_test.go
  resolver/parallel_best_resolver_test.go
  resolver/query_logging_resolver.go
  resolver/query_logging_resolver_test.go
  resolver/resolver_suite_test.go
  resolver/resolver_test.go
  resolver/upstream_resolver_test.go
  server/server_suite_test.go
  server/server_test.go
  util/bootstrap_test.go
  util/common_test.go
  util/util_suite_test.go
Labels: dependencies

#457 docs/config.yml: default for tlsPort is 853
  docs/config.yml
Labels: documentation

#449 Add rewrite support to custom DNS
  README.md
  config/config.go
  docs/config.yml
  docs/configuration.md
  resolver/blocking_resolver.go
  resolver/blocking_resolver_test.go
  resolver/caching_resolver_test.go
  resolver/client_names_resolver_test.go
  resolver/conditional_upstream_resolver.go
  resolver/conditional_upstream_resolver_test.go
  resolver/custom_dns_resolver.go
  resolver/custom_dns_resolver_test.go
  resolver/hosts_file_resolver_test.go
  resolver/ipv6_disabling_resolver_test.go
  resolver/metrics_resolver_test.go
  resolver/mocks.go
  resolver/noop_resolver.go
  resolver/noop_resolver_test.go
  resolver/parallel_best_resolver.go
  resolver/parallel_best_resolver_test.go
  resolver/query_logging_resolver_test.go
  resolver/resolver.go
  resolver/resolver_test.go
  resolver/rewriter_resolver.go
  resolver/rewriter_resolver_test.go
  server/server.go
Labels: enhancement

#467 CustomDNS: parameter "filterUnmappedTypes" to allow/disable forwarding to the upstream resolver
  config/config.go
  docs/config.yml
  docs/configuration.md
  go.mod
  go.sum
  resolver/custom_dns_resolver.go
  resolver/custom_dns_resolver_test.go
Labels: enhancement
