Repository 0xERR0R/blocky, pull requests merged in 2023-11, with the labels that each got.

#1225 fix: ANSI color codes being printed on Windows
  go.mod
  log/logger.go
  server/server_config_trigger_windows.go
Labels: 🐞 bug

#1220 devcontainer & unit test refactoring
  .devcontainer/devcontainer.json
  .devcontainer/scripts/generate-lcov.sh
  .devcontainer/scripts/postStart.sh
  .github/workflows/makefile.yml
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  Makefile
  cache/stringcache/chained_grouped_cache_test.go
  cache/stringcache/in_memory_grouped_cache_test.go
  cache/stringcache/string_caches_test.go
  cmd/healthcheck_test.go
  cmd/lists_test.go
  cmd/serve_test.go
  helpertest/helper.go
  lists/list_cache_test.go
  resolver/hosts_file_resolver_test.go
  resolver/parallel_best_resolver_test.go
  resolver/strict_resolver_test.go
  server/server_test.go
Labels: 🧰 technical debts

#1232 Bugfix/readme
  .github/workflows/close_stale.yml
  .github/workflows/delete-workflow-runs.yml
  .github/workflows/fork-sync.yml
  .github/workflows/mirror-repo.yml
Labels: 🐞 bug

#1235 feat: add ginkgolinter to golangci
  .golangci.yml
  api/api_interface_impl_test.go
  lists/downloader_test.go
Labels: 🔨 enhancement

#1234 Bugfix/GitHub workflows
  .devcontainer/devcontainer.json
  .github/workflows/close_stale.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/delete-workflow-runs.yml
  .github/workflows/docs.yml
  .github/workflows/fork-sync.yml
  .github/workflows/mirror-repo.yml
  .github/workflows/release.yml
Labels: 🐞 bug

#1245 Unit test refactoring
  .devcontainer/devcontainer.json
  .devcontainer/scripts/generate-lcov.sh
  .devcontainer/scripts/runItOnGo.sh
  .dockerignore
  .gitignore
  .golangci.yml
  .vscode/settings.json
  helpertest/mock_call_sequence.go
  lists/list_cache_test.go
  lists/parsers/parser_test.go
  redis/redis_test.go
  server/server_test.go
Labels: 🧰 technical debts

#1255 fix: log.privacy option no longer hides domain names being resolved
  e2e/basic_test.go
  resolver/conditional_upstream_resolver.go
  resolver/hosts_file_resolver.go
  resolver/query_logging_resolver.go
  resolver/rewriter_resolver.go
Labels: 🐞 bug

#1221 feat: add upstream strategy `random`
  api/api_client.gen.go
  api/api_server.gen.go
  api/api_types.gen.go
  config/config.go
  config/config_enum.go
  config/upstreams.go
  config/upstreams_test.go
  docs/config.yml
  docs/configuration.md
  resolver/blocking_resolver.go
  resolver/bootstrap.go
  resolver/bootstrap_test.go
  resolver/caching_resolver.go
  resolver/conditional_upstream_resolver.go
  resolver/custom_dns_resolver.go
  resolver/hosts_file_resolver.go
  resolver/parallel_best_resolver.go
  resolver/parallel_best_resolver_test.go
  resolver/resolver.go
  resolver/strict_resolver.go
  resolver/strict_resolver_test.go
  server/server.go
  server/server_test.go
Labels: 🔨 enhancement

#1263 symbol name refactoring
  config/config.go
  config/config_test.go
  config/ecs.go
  config/ecs_test.go
  config/sudn.go
  config/sudn_test.go
  resolver/ecs_resolver.go
  resolver/ecs_resolver_test.go
  resolver/ede_resolver.go
  resolver/ede_resolver_test.go
  resolver/fqdn_only_resolver.go
  resolver/fqdn_only_resolver_test.go
  resolver/sudn_resolver.go
  resolver/sudn_resolver_test.go
  server/server.go
Labels: 🧰 technical debts

#1271 Refactoring Redis
  .devcontainer/devcontainer.json
  .golangci.yml
  .vscode/settings.json
  api/api_interface_impl.go
  api/api_interface_impl_test.go
  config/config.go
  config/config_test.go
  config/redis.go
  config/redis_test.go
  redis/redis.go
  redis/redis_test.go
  resolver/blocking_resolver.go
  resolver/blocking_resolver_test.go
  resolver/caching_resolver.go
  resolver/caching_resolver_test.go
  resolver/parallel_best_resolver_test.go
  resolver/strict_resolver_test.go
  server/server.go
  util/context.go
  util/context_test.go
Labels: 🧰 technical debts

#1277 Refactoring server.go
  cmd/serve.go
  config/config_test.go
  helpertest/helper.go
  resolver/parallel_best_resolver_test.go
  server/server.go
  server/server_test.go
Labels: 🧰 technical debts

#1281 Refactoring: FileDownloader
  .golangci.yml
  e2e/basic_test.go
  e2e/blocking_test.go
  e2e/containers.go
  e2e/e2e_suite_test.go
  e2e/metrics_test.go
  e2e/querylog_test.go
  e2e/redis_test.go
  e2e/upstream_test.go
  lists/downloader.go
  lists/downloader_test.go
  lists/list_cache.go
  lists/list_cache_test.go
  lists/sourcereader.go
  resolver/hosts_file_resolver.go
Labels: 🧰 technical debts
