Repository 0xERR0R/blocky, pull requests merged in 2023-03, with the labels that each got.

#909 feat: add cache entire DNS response (#833)
  resolver/caching_resolver.go
Labels: enhancement

#913 feat: client name in clientGroupsBlock should not be case-sensitive
  resolver/blocking_resolver.go
  resolver/blocking_resolver_test.go
  util/common.go
Labels: enhancement

#915 fix: wrong prefetch metrics if bootstrap is enabled (#891)
  resolver/bootstrap.go
  resolver/caching_resolver.go
Labels: bug

#932 chore(test): fix freezing test
  resolver/bootstrap_test.go
Labels: 🧰 technical debts

#933 refactor: add generics to ExpiringCache
  cache/expirationcache/cache_interface.go
  cache/expirationcache/expiration_cache.go
  cache/expirationcache/expiration_cache_test.go
  resolver/blocking_resolver.go
  resolver/caching_resolver.go
  resolver/caching_resolver_test.go
  resolver/client_names_resolver.go
Labels: 🧰 technical debts

#935 chore(deps): remove obsolete replace for testcontainers
  go.mod
  go.sum
Labels: ⚙️ dependencies

#931 chore(build): update golangci-lint
  Makefile
  api/api.go
  go.mod
  go.sum
  server/server.go
Labels: ⚙️ dependencies

#934 update weightedrand to v2
  go.mod
  go.sum
  resolver/parallel_best_resolver.go
  resolver/parallel_best_resolver_test.go
Labels: ⚙️ dependencies

#937 update Go to 1.20
  go.mod
  go.sum
Labels: ⚙️ dependencies

#943 chore(deps): update opencontainers (CVE-2019-19921)
  go.mod
  go.sum
Labels: ⚙️ dependencies

#942 chore(build): use v prefixed release versions (#858, #806)
  .goreleaser.yml
Labels: 📙 documentation, 🧰 technical debts

#944 refactor: use groupedCache to optimize cache access
  cache/stringcache/chained_grouped_cache.go
  cache/stringcache/chained_grouped_cache_test.go
  cache/stringcache/grouped_cache_interface.go
  cache/stringcache/in_memory_grouped_cache.go
  cache/stringcache/in_memory_grouped_cache_test.go
  cache/stringcache/string_caches.go
  cache/stringcache/string_caches_benchmark_test.go
  cache/stringcache/string_caches_test.go
  lists/list_cache.go
  lists/list_cache_test.go
  resolver/blocking_resolver.go
Labels: 🧰 technical debts

#951 GitHub Actions Update
  .github/workflows/codeql-analysis.yml
  .github/workflows/development-docker.yml
  .github/workflows/makefile.yml
Labels: 🧰 technical debts

#963 fix: support IDNA in lists
  lists/parsers/hosts.go
  lists/parsers/hosts_test.go
Labels: 🔨 enhancement
