Repository 0xERR0R/blocky, pull requests merged in 2023-12, with the labels that each got.

#1302 feat(resolver): race UDP and TCP when connecting upstream
  resolver/upstream_resolver.go
  resolver/upstream_resolver_test.go
  server/server.go
Labels: 🔨 enhancement

#1312 fix(rewrite): support the case where upstream doesn't echo the question
  resolver/rewriter_resolver.go
  resolver/rewriter_resolver_test.go
Labels: 🐞 bug

#1315 Refactoring/config struct names
  .vscode/settings.json
  config/blocking.go
  config/caching.go
  config/caching_test.go
  config/config.go
  config/config_test.go
  config/filtering.go
  config/filtering_test.go
  config/hosts_file.go
  config/hosts_file_test.go
  config/metrics.go
  config/metrics_test.go
  config/query_log.go
  config/query_log_test.go
  lists/downloader.go
  lists/downloader_test.go
  lists/list_cache.go
  lists/list_cache_benchmark_test.go
  lists/list_cache_test.go
  metrics/metrics.go
  resolver/blocking_resolver_test.go
  resolver/bootstrap.go
  resolver/bootstrap_test.go
  resolver/caching_resolver.go
  resolver/caching_resolver_test.go
  resolver/filtering_resolver.go
  resolver/filtering_resolver_test.go
  resolver/hosts_file_resolver.go
  resolver/hosts_file_resolver_test.go
  resolver/metrics_resolver.go
  resolver/metrics_resolver_test.go
  resolver/mocks_test.go
  resolver/query_logging_resolver.go
  resolver/query_logging_resolver_test.go
  server/server_test.go
Labels: 🧰 technical debts
