Repository 0xERR0R/blocky, pull requests merged in 2023-10, with the labels that each got.

#1179 Feature/devcontainer
  .devcontainer/devcontainer.json
  .dockerignore
  .gitattributes
Labels: 🔨 enhancement

#1184 remove go version in devcontainer file
  .devcontainer/devcontainer.json
Labels: 🧰 technical debts

#1188 chore: make test non-blocking
  config/config_test.go
Labels: 🧰 technical debts

#1189 chore: improve database writer tests
  querylog/database_writer_test.go
Labels: 🧰 technical debts

#1187 refactor: pass context for goroutine shutdown
  cache/expirationcache/expiration_cache.go
  cache/expirationcache/expiration_cache_test.go
  cache/expirationcache/prefetching_cache.go
  cache/expirationcache/prefetching_cache_test.go
  cmd/serve.go
  cmd/serve_test.go
  config/config.go
  config/config_test.go
  lists/list_cache.go
  lists/list_cache_benchmark_test.go
  lists/list_cache_test.go
  querylog/database_writer.go
  querylog/database_writer_test.go
  resolver/blocking_resolver.go
  resolver/blocking_resolver_test.go
  resolver/bootstrap.go
  resolver/bootstrap_test.go
  resolver/caching_resolver.go
  resolver/caching_resolver_test.go
  resolver/client_names_resolver.go
  resolver/client_names_resolver_test.go
  resolver/conditional_upstream_resolver_test.go
  resolver/hosts_file_resolver.go
  resolver/hosts_file_resolver_test.go
  resolver/mocks_test.go
  resolver/parallel_best_resolver_test.go
  resolver/query_logging_resolver.go
  resolver/query_logging_resolver_test.go
  resolver/resolver_test.go
  server/server.go
  server/server_config_trigger.go
  server/server_test.go
Labels: 🔨 enhancement, 🧰 technical debts

#1191 opencontainer labels
  Dockerfile
Labels: 🧰 technical debts

#1192 Fix/opencontainer labels
  .github/workflows/development-docker.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
Labels: 🐞 bug

#1196 feat: reduce DNS response cache memory consumption
  resolver/caching_resolver.go
Labels: 🔨 enhancement
