Repository 0xERR0R/blocky, pull requests merged in 2024-04, with the labels that each got.

#1414 fix: use proxy env vars via Go default HTTP Transport values
  helpertest/http.go
  lists/downloader_test.go
  resolver/bootstrap.go
  resolver/bootstrap_test.go
  resolver/upstream_resolver.go
  resolver/upstream_resolver_test.go
  util/http.go
  util/http_test.go
Labels: 🐞 bug

#1445 Feature: binary build workflow
  .github/workflows/build-bin.yml
  .github/workflows/makefile.yml
Labels: 🔨 enhancement

#1447 Refactoring/linter
  Makefile
  cache/stringcache/string_caches.go
  cmd/blocking.go
  config/migration/migration.go
  go.mod
  lists/downloader.go
  metrics/metrics_event_publisher.go
  resolver/blocking_resolver.go
  resolver/mocks_test.go
  resolver/query_logging_resolver.go
  server/server_endpoints.go
Labels: 🧰 technical debts
